name: tarahib_mobile_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  data_table_2: ^2.5.8
  flutter_screenutil: ^5.9.0
  nb_utils: ^6.0.6
  form_validator: ^2.1.1
  redacted: ^1.0.11
  dio: ^5.3.3
  dio_cache_interceptor_hive_store: ^3.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  talker_dio_logger: ^2.3.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

